### ISSUE TITLE
InternalOAuthError: Failed to obtain access token

### ISSUE THREAD

**Issue by dSecret** [iamshaunjp/oauth-playlist#1]
`InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (D:\nodejsServer\oauth-playlist\node_modules\passport-oauth2\lib\strategy.js:379:17)
    at D:\nodejsServer\oauth-playlist\node_modules\passport-oauth2\lib\strategy.js:166:45
    at D:\nodejsServer\oauth-playlist\node_modules\oauth\lib\oauth2.js:191:18
    at ClientRequest.<anonymous> (D:\nodejsServer\oauth-playlist\node_modules\oauth\lib\oauth2.js:162:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

After cloning the repo if I try to access the features inside lesson-15 branch then this error pops out.
Please help me out!!
Thanks`

**Comment by shanewils92** [comment]
Hey @dSecret, we are now up to part 19 in the series, are you still facing this problem or has it passed?

I have followed the steps provided and seem unable to reproduce the error. Remember that when cloning the repository, ensure you are providing your own key(s)**&ast;** and making necessary changes to the code.

**&ast;**Refer to episodes [6](https://www.youtube.com/watch?v=9x66l93iEW0) and [8](https://www.youtube.com/watch?v=or1_A4sJ-oY) for creating Google OAuth credentials.

**Comment by peterlxb** [comment]
I have the same error ,I checked my clientID and keys many times,
