### ISSUE TITLE
lesson-12 Passport error:  TokenError: Bad Request 

### ISSUE THREAD

**Issue by lmilliken** [iamshaunjp/oauth-playlist#12]
This is related to [this issue](https://github.com/jaredhanson/passport-google-oauth2/issues/15).

The error starts appearing on the lesson-12 branch.

After clicking the Google account to authenticate with, the app spins for a while before showing the below error:
```
TokenError: Bad Request
    at Strategy.OAuth2Strategy.parseErrorResponse (C:\Users\milliken\Documents\GitHub\learning\oauth-playlist\node_modules\passport-oauth2\lib\strategy.js:329:12)
    at Strategy.OAuth2Strategy._createOAuthError (C:\Users\milliken\Documents\GitHub\learning\oauth-playlist\node_modules\passport-oauth2\lib\strategy.js:376:16)
    at C:\Users\milliken\Documents\GitHub\learning\oauth-playlist\node_modules\passport-oauth2\lib\strategy.js:166:45
    at C:\Users\milliken\Documents\GitHub\learning\oauth-playlist\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (C:\Users\milliken\Documents\GitHub\learning\oauth-playlist\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\milliken\Documents\GitHub\learning\oauth-playlist\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)

**Comment by lmilliken** [comment]
Just continue to the rest of the video tutorials, eventually once all of passport is hooked up, the error is resovled.

**Comment by Hameed098** [comment]
TokenError: Bad Request
    at Strategy.OAuth2Strategy.parseErrorResponse (F:\sampleweb\node_modules\passport-oauth2\lib\strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (F:\sampleweb\node_modules\passport-oauth2\lib\strategy.js:405:16)
    at F:\sampleweb\node_modules\passport-oauth2\lib\strategy.js:175:45
    at F:\sampleweb\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (F:\sampleweb\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (F:\sampleweb\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
